### PR TITLE
Fix update-channel failing

### PR DESCRIPTION
**Pull request by williewillus**
wrong arity call to update-channel

### CODE REVIEW

**Comment by spdegabrielle** [comment]
@williewillus Do have a test script? I'd like to try this out on the racket discord!

**Comment by williewillus** [comment]
@spdegabrielle I'm using this library in a project called R16, which is a trick bot for Discord. Basically, it allows users to register and execute short code snippets in a sandbox from Discord commands.

https://git.sr.ht/~williewillus/r16/

**Comment by nitros12** [comment]
Thanks for fixing this, I don't have much interest in working on this lib (I'm using my haskell library nowadays), so would you like to be added as a repo collaborator?

**Comment by williewillus** [comment]
That'd be great, I had to plans to add support for V8 of the gateway api (so gateway intents would be usable)

**Comment by spdegabrielle** [comment]
@williewillus sorry for contacting you via GitHub - I couldn't find another mechanism to message you
Hi Vincent, I recently asked you about racket-cord, and you kindly pointed me to your r16 bot repo> I'm thinking about lightly modifying it and including it in the racket-templates repository as a bot example that new racketeers could work from.  Would you be willing to provide a suitable licence? Since the goal is reuse I'd prefer MIT or apache2 - but it is up to you.
Kind regards, 

Stephen

**Comment by williewillus** [comment]
@spdegabrielle sure, we updated it to MIT. Here's the project page on sourcehut for posting https://sr.ht/~williewillus/r16/

**Pull request merged**
